version: "3.7"

services:
  github-search-vue-v2:
    build: .
    image: nodejs:15
    container_name: github-search-vue-v2
    restart: unless-stopped
    ports:
      - 4000:4000
    volumes:
      - .:/app
